#faça um programa que leia a tabuada de um numero
n= int(input("Enter a number:"))
print("Multiplication Table")
print("{}".format(n*0))
print("{}".format(n*1))
print("{}".format(n*2))
print("{}".format(n*3))
print("{}".format(n*4))
print("{}".format(n*5))
print("{}".format(n*6))
print("{}".format(n*7))
print("{}".format(n*8))
print("{}".format(n*9))
print("{}".format(n*10))
